In [2]:
import torch
from data_loader import *
from model import *
from trainer import *
from tqdm import tqdm

In [5]:
dataset = recSysDataset(max_len=20, root = "./data/kcore_5_collated.txt")
train_data = train_val_test_split(dataset, split=(.5,.45,.05), mode = "train") #change back to .85,.10,.05
val_data = train_val_test_split(dataset, split=(.5,.45,.05), mode = "val")
test_data = train_val_test_split(dataset, split=(.5,.45,.05), mode = "test")
dataloader = torch.utils.data.DataLoader(train_data, batch_size = 16, shuffle = True)
tqdm.write("Dataloader done")

1169798it [00:16, 135362.95it/s]

In [ ]:
%load_ext autoreload
%autoreload 2

In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
model = recSysNet(device,1569974,120,5,1,.1,bidirectional=False)
print(model)
model.to(device)
print(model.device)
tqdm.write("Model instantiated")
trainer = Trainer(model, BPRLoss, [], Adam(model.parameters(),lr=.001), dataloader)
tqdm.write("Training...")
trainer.train()

recSysNet(
  (embed): Embedding(1569974, 120)
  (lstm): LSTM(120, 5, batch_first=True)
  (dropout): Dropout(p=0.1, inplace=False)
  (fc): Linear(in_features=5, out_features=1569974, bias=True)
)


RuntimeError: ignored

In [ ]:
target = torch.arange(0,4).reshape((2,2))
negatives = target.clone()
while (negatives[negatives==target]).sum():
  print(negatives==target,negatives,target)
  negatives[negatives==target] = torch.randint(2,200,size=negatives[negatives==target].size())

In [ ]:
a = torch.arange(16).reshape((4,4))
a

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])

In [ ]:
torch.roll(a,-1,1) #target

tensor([[ 1,  2,  3,  0],
        [ 5,  6,  7,  4],
        [ 9, 10, 11,  8],
        [13, 14, 15, 12]])

In [ ]:
torch.roll(a,-1,1)[:,1:-1]

tensor([[ 1,  2,  3],
        [ 5,  6,  7],
        [ 9, 10, 11],
        [13, 14, 15]])

In [ ]:
#start token,item 1, item 2... padding